_recursive_: true
_convert_: all

moving_image_key: moving_image
fixed_image_key: fixed_image
moving_label_key: moving_label
fixed_label_key: fixed_label


intensity_transform:
  _target_: monai.transforms.ScaleIntensityRanged
  keys: 
    - ${datamodule.config.transforms.fixed_image_key}
    - ${datamodule.config.transforms.moving_image_key}
  a_min: -1200.0 
  a_max: 400.0
  b_min: 0.0
  b_max: 1.0
  clip: true

train_transforms:
  - _target_:  monai.transforms.LoadImaged
    keys: 
      - ${datamodule.config.transforms.fixed_image_key}
      - ${datamodule.config.transforms.moving_image_key}
      - ${datamodule.config.transforms.fixed_label_key}
      - ${datamodule.config.transforms.moving_label_key}
    ensure_channel_first: true
  - ${datamodule.config.transforms.intensity_transform}
  - _target_: monai.transforms.Resized
    keys: 
      - ${datamodule.config.transforms.fixed_image_key}
      - ${datamodule.config.transforms.moving_image_key}
      - ${datamodule.config.transforms.fixed_label_key}
      - ${datamodule.config.transforms.moving_label_key}
    mode:
      - trilinear
      - trilinear
      - nearest
      - nearest
    align_corners: 
      - true
      - true
      - null
      - null
    spatial_size: ${datamodule.config.spatial_size}
  - _target_: monai.transforms.RandAffined
    keys: 
      - ${datamodule.config.transforms.fixed_image_key}
      - ${datamodule.config.transforms.moving_image_key}
      - ${datamodule.config.transforms.fixed_label_key}
      - ${datamodule.config.transforms.moving_label_key}
    mode:
      - bilinear
      - bilinear
      - nearest
      - nearest
    prob: 0.8
    shear_range: 0.2
    translate_range: ${datamodule.config.translate_range}
    rotate_range: 0.26179939 # np.pi / 180 * 15,
    scale_range: 0.2
    padding_mode:
      - zeros
      - zeros
      - zeros
      - zeros

val_transforms:
  _target_: monai.transforms.Compose
  transforms: 
    - _target_:  monai.transforms.LoadImaged
      keys: 
        - ${datamodule.config.transforms.fixed_image_key}
        - ${datamodule.config.transforms.moving_image_key}
        - ${datamodule.config.transforms.fixed_label_key}
        - ${datamodule.config.transforms.moving_label_key}
      ensure_channel_first: true
    - ${datamodule.config.transforms.intensity_transform}
    - _target_: monai.transforms.Resized
      keys: 
        - ${datamodule.config.transforms.fixed_image_key}
        - ${datamodule.config.transforms.moving_image_key}
        - ${datamodule.config.transforms.fixed_label_key}
        - ${datamodule.config.transforms.moving_label_key}
      mode:
        - trilinear
        - trilinear
        - nearest
        - nearest
      align_corners: 
        - true
        - true
        - null
        - null
      spatial_size: ${datamodule.config.spatial_size}
