train_dataloader:
  _target_: torch.utils.data.DataLoader 
  batch_size: ${datamodule.config.batch_size}
  num_workers: ${datamodule.config.num_workers}
  shuffle: True
  # pin_memory: True
  drop_last: True

val_dataloader:
  _target_: torch.utils.data.DataLoader 
  batch_size: ${datamodule.config.batch_size}
  num_workers: ${datamodule.config.num_workers}
  shuffle: False
  # pin_memory: True
  drop_last: False

test_dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${datamodule.config.batch_size}
  num_workers: ${datamodule.config.num_workers}
  shuffle: False
  # pin_memory: True
  drop_last: False
