train_dataloader:
  _target_: monai.data.DataLoader
  batch_size: 1
  num_workers: ${datamodule.config.num_workers}
  shuffle: True
  collate_fn: 
    _target_: hydra.utils.get_object
    path: monai.data.utils.no_collation
  # drop_last: True
  persistent_workers: False
  pin_memory: False

val_dataloader:
  _target_: monai.data.DataLoader
  batch_size: 1
  num_workers: ${datamodule.config.num_workers}
  shuffle: False
  collate_fn: 
    _target_: hydra.utils.get_object
    path: monai.data.utils.no_collation
  # drop_last: False
  persistent_workers: False
  pin_memory: False

test_dataloader:
  _target_: monai.data.DataLoader
  batch_size: 1
  num_workers: ${datamodule.config.num_workers}
  shuffle: False
  collate_fn: 
    _target_: hydra.utils.get_object
    path: monai.data.utils.no_collation
  # drop_last: False
  persistent_workers: False
  pin_memory: False