- _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: val_dice
  mode: max
  patience: ${scheduling.early_stopping_patience}
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: '{epoch}-{val_tre:.3f}-{val_dice:.3f}'
  save_top_k: 1
  verbose: True
  monitor: val_dice
  mode: max
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: '{epoch}-{val_tre:.3f}-{val_dice:.3f}'
  save_top_k: 1
  verbose: True
  monitor: val_tre
  mode: min
  save_last: True
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
