- _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
  monitor: ${scheduling.monitor}
  mode: ${scheduling.monitor_mode}
  patience: ${scheduling.early_stopping_patience}
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  filename: ${scheduling.save_filename}
  save_top_k: 1
  verbose: True
  monitor: ${scheduling.monitor}
  mode: ${scheduling.monitor_mode}
  save_last: True
- _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: epoch
