experiment: registration

lightning_module:
  _target_: hydra.utils.get_class
  path: lightning_modules.models.registration_module.RegistrationModule

seed: 0
seed_monai: 0
use_low_prec_matmul: false # set true for A100 GPU for faster training

defaults:
  - loss: registration_multitarget
  - model: registration_unet
  - datamodule: registration_datamodule
  - optimizer: adam_reg
  - metric: dice_reg
  - logger: loggers
  - scheduling: scheduler_reg
  - trainer: default_trainer
  - hydra: default_hydra
  - override hydra/hydra_logging: disabled
  # allows to override any parameter from this config
  - _self_