_target_: pytorch_lightning.Trainer
_recursive_: true
_convert_: all

devices: [0]
# devices: auto
accelerator: gpu
num_sanity_val_steps: 0
max_epochs: ${scheduling.epochs}
callbacks: ${scheduling.callbacks}
check_val_every_n_epoch: ${scheduling.check_val_every_n_epoch}
precision: 16-mixed
log_every_n_steps: 25