_recursive_: true
_convert_: all

monitor: val_dice
monitor_mode: max
early_stopping_patience: 35
save_filename: '{epoch}-{val_dice:.3f}-{val_iou:.3f}'

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: max
  patience: 15
  factor: 0.5
  min_lr: 0.0000001

additional_params:
  monitor: ${scheduling.monitor}
  interval: epoch
  frequency: 2

check_val_every_n_epoch: ${scheduling.additional_params.frequency}
epochs: 1000

defaults:
  - callbacks: default_callbacks