_recursive_: true
_convert_: all

monitor: val_dice
monitor_mode: max
early_stopping_patience: 150
save_filename: '{epoch}-{val_dice:.3f}-{val_iou:.3f}'

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: max
  patience: 40
  factor: 0.5
  min_lr: 0.0000001

# scheduler:
#   _target_: schedulers.polylr.PolyLRScheduler
#   initial_lr: ${optimizer.lr}
#   max_steps: ${scheduling.epochs}

additional_params:
  monitor: ${scheduling.monitor}
  interval: epoch
  frequency: 1

check_val_every_n_epoch: ${scheduling.additional_params.frequency}
epochs: 5000

defaults:
  - callbacks: default_callbacks
